### ISSUE TITLE
Yarn build error.

### ISSUE THREAD

**Issue by trypzz** [milutinke/sqcp#14]
Hi,

I not frontend developer and can't fix this issue. Can you help me? What i dong wrong? Going by steps from setup guide.

yarn build

yarn run v1.22.19
$ vue-cli-service build
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

⠹  Building for production...Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/steam/sqcp/frontend/squad-control-panel/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
⠸  Building for production.../home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:114
			throw e;
			^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:186:6
    at context.callback (/home/steam/sqcp/frontend/squad-control-panel/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/cache-loader/dist/index.js:240:7
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/neo-async/async.js:2830:7
    at done (/home/steam/sqcp/frontend/squad-control-panel/node_modules/neo-async/async.js:2865:11)
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/neo-async/async.js:2818:7
    at /home/steam/sqcp/frontend/squad-control-panel/node_modules/cache-loader/dist/index.js:229:9 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.4.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Any ideas?

Using ubuntu 22.04

**Comment by milutinke** [comment]
You need to set the following environment variable in order to fix this.

```
export NODE_OPTIONS=--openssl-legacy-provider
```
You can add it to .bashrc and then do `source .bashrc`
(Or to other profile file if you use another shell).

Or if you want to do it once, just add it as a command line argument to the yarn build command:
```
yarn build --openssl-legacy-provider
```

**Comment by trypzz** [comment]
Done with:

`export NODE_OPTIONS=--openssl-legacy-provider`

Just as parameter in yarn build command - not working (dont know why, same error)

Thanks for help.
